# David Walshe
# 07-Apr-2021

language: python
cache: pip
python:
    - "3.7"
install:
    - pip install -r requirements/dev.txt
script:
    - pytest --cov --cov-report=term-missing
after_success:
    - coveralls
deploy:
    provider: pypi
    username: "__token__"
    password: $PYPI_TEST_TOKEN
    server: https://test.pypi.org/legacy/
    on:
        repo: DavidWalshe93/SLA-CLI
        branches:
            only:
                - dev