# David Walshe
# 07-Apr-2021

language: python
cache: pip
python:
    - "3.7"
install:
    - pip install -r requirements.txt
script:
    - pytest --cov=src --cov-report=term-missing
after_success:
    - coveralls